### ISSUE TITLE
Admin sign_in raise an ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by mdouchement** [FranckKe/mersea#104]
Linked to the merge of this PR https://github.com/FranckKe/mersea/pull/89

**Comment by mdouchement** [comment]
This piece of code makes the admin login fail

https://github.com/FranckKe/mersea/blob/6f50369ec4dfbe2fb46aa6e0e1a14f1442f2d840/app/controllers/application_controller.rb#L52-L54

**Comment by mdouchement** [comment]
- https://github.com/plataformatec/devise/wiki/How-To:-redirect-to-a-specific-page-on-successful-sign_in,-sign_out,-and-or-sign_up
- https://github.com/plataformatec/devise/wiki/How-To:-Redirect-to-a-specific-page-on-successful-sign-in-and-sign-out
- (where they say do not use referrer) https://github.com/plataformatec/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update

**Comment by FranckKe** [comment]
Further doc
- https://github.com/plataformatec/devise/wiki/How-To:--Redirect-with-locale-after-authentication-failure
- https://github.com/plataformatec/devise/wiki/How-To:-Add-:confirmable-to-Users#redirecting-user
