### ISSUE TITLE
[V2] Reset password

### ISSUE THREAD

**Issue by mdouchement** [FranckKe/mersea#137]
The URL in the sent email is deprecated and will not work with the API mode.
Pay attention to Admin reset password too.

- [ ] Users, here are two choices:
  - Use Devise stuff like Admin
  - Use our own views has defined in #125 (The API route is already implemented)
- [x] Admin #139 (compatible with Mersea v1)
- [ ] [Postmark i18n](https://postmarkapp.com/support/article/1100-templates-faq)

**Comment by mdouchement** [comment]
https://github.com/scienceexchange/postmark_mailer

**Comment by mdouchement** [comment]
Add a secrets with the frontend url format abd update https://github.com/FranckKe/mersea/blob/pu-2.0/app/mailers/postmark_devise_mailer.rb#L9

**Comment by FranckKe** [comment]
Closed in https://github.com/FranckKe/mersea/pull/232
