### ISSUE TITLE
[V2] Move to Active Storage

### ISSUE THREAD

**Issue by mdouchement** [FranckKe/mersea#145]
- Drop Paperclip and use [Active Storage](http://guides.rubyonrails.org/active_storage_overview.html)
  - https://evilmartians.com/chronicles/rails-5-2-active-storage-and-beyond
- Add thumbnail

⚠️ Data migration
- https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md

**Comment by FranckKe** [comment]
#152
