### ISSUE TITLE
[V2] SignIn/Login form

### ISSUE THREAD

**Issue by mdouchement** [FranckKe/mersea#179]
1. Create a view/form `Login.vue`
2. After sign in, retrieve the Bearer token from headers and inject it in Axios
3. Backup it in the local storage

- Check if the token is in the local storage before before displaying:
  - the login page
  - the user settings
  - the user reports

Resources:
- https://blog.sqreen.io/authentication-best-practices-vue/
- https://github.com/websanova/vue-auth
  - Vue.use: https://github.com/websanova/vue-auth/blob/master/docs/Installation.md#install-2x
  - default values https://github.com/websanova/vue-auth/blob/master/src/auth.js#L475-L562
    - https://github.com/websanova/vue-auth/blob/master/docs/Options.md
  - We will need to update these default values ^  in order to match our API

**Comment by FranckKe** [comment]
#180
