### ISSUE TITLE
[v2] The state of AddReport form is not reseted at the end

### ISSUE THREAD

**Issue by mdouchement** [FranckKe/mersea#211]
Steps to reproduce:
1. Add a report
2. Do all report steps
3. Close the report form
4. Add a new report

=> The form is not at the first step but at the last.

**Comment by FranckKe** [comment]
Known issue. Step cannot be changed programmatically.

Requires customizing the lib.

**Comment by mdouchement** [comment]
Now it's tracked ;)

Could we not track the `POST /reports` and the on-close events?
